feat: update mariadb to 1%10.11.6

diff --git a/debian/mariadb-server.preinst b/debian/mariadb-server.preinst
--- a/debian/mariadb-server.preinst
+++ b/debian/mariadb-server.preinst
@@ -7,43 +7,62 @@
 #        * <old-preinst> abort-upgrade <new-version>
 #
 
+# shellcheck source=/dev/null
 . /usr/share/debconf/confmodule
 
 # Just kill the invalid insserv.conf.d directory without fallback
-if [ -d "/etc/insserv.conf.d/mariadb/" ]; then
-    rm -rf "/etc/insserv.conf.d/mariadb/"
+if [ -d "/etc/insserv.conf.d/mariadb/" ]
+then
+  rm -rf "/etc/insserv.conf.d/mariadb/"
 fi
 
-if [ -n "$DEBIAN_SCRIPT_DEBUG" ]; then set -v -x; DEBIAN_SCRIPT_TRACE=1; fi
+if [ -n "$DEBIAN_SCRIPT_DEBUG" ]
+then
+  set -v -x
+  DEBIAN_SCRIPT_TRACE=1
+fi
 ${DEBIAN_SCRIPT_TRACE:+ echo "#42#DEBUG# RUNNING $0 $*" 1>&2 }
 
 export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
 mysql_datadir=/var/lib/mysql
 mysql_upgradedir=/var/lib/mysql-upgrade
 
+MARIADBD_USERS="root"
+
+# Check if user 'mysql' exists before referring to it in pgrep
+# to avoid pgrep erroring on 'invalid user name'
+if id mysql >/dev/null 2>&1
+then
+  MARIADBD_USERS="$MARIADBD_USERS,mysql"
+fi
+
 # Try to stop the server in a sane way. If it does not success let the admin
 # do it himself. No database directories should be removed while the server
 # is running! Another mariadbd in e.g. a different chroot is fine for us.
 stop_server() {
-    # Return immediately if there are no mysqld processes running on a host
-    # (leave containerized processes with the same name in other namespaces)
-    # as there is no point in trying to shutdown in that case.
-    if ! pgrep -x --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
+  # Return immediately if there are no mysqld processes running on a host
+  # (leave containerized processes with the same name in other namespaces)
+  # as there is no point in trying to shutdown in that case.
+  if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null
+  then
+    return
+  fi
 
-    set +e
-    invoke-rc.d mariadb stop
-    invoke-rc.d mysql stop # Backwards compatibility
-    errno=$?
-    set -e
+  set +e
+  invoke-rc.d mariadb stop
+  invoke-rc.d mysql stop # Backwards compatibility
+  errno=$?
+  set -e
 
-    # systemctl could emit exit code 100=no init script (fresh install)
-    if [ "$errno" != 0 -a "$errno" != 100 ]; then
-      echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
-      echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
-      echo "Stop it yourself and try again!" 1>&2
-      db_stop
-      exit 1
-    fi
+  # systemctl could emit exit code 100=no init script (fresh install)
+  if [ "$errno" != 0 ] && [ "$errno" != 100 ]
+  then
+    echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+    echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
+    echo "Stop it yourself and try again!" 1>&2
+    db_stop
+    exit 1
+  fi
 }
 
 ################################ main() ##########################
@@ -56,7 +75,7 @@ max_upgradeable_version=5.7
 # Check if a flag file is found that indicates a previous MariaDB or MySQL
 # version was installed. If multiple flags are found, check which one was
 # the biggest version number.
-for flag in $mysql_datadir/debian-*.flag
+for flag in "$mysql_datadir"/debian-*.flag
 do
 
   # The for loop leaves $flag as the query string if there are no results,
@@ -67,6 +86,9 @@ do
     break
   fi
 
+  # The whole flag_version thing should be rewritten, so ignore minor Shellcheck
+  # nag for now
+  # shellcheck disable=SC2001
   flag_version=$(echo "$flag" | sed 's/.*debian-\([0-9\.]\+\).flag/\1/')
 
   # Initialize value if empty
@@ -91,7 +113,7 @@ done
 # Downgrade is detected if the flag version is bigger than $this_version
 # (e.g. 10.1 > 10.0) or the flag version is smaller than 10.0 but bigger
 # than $max_upgradeable_version.
-if [ ! -z "$found_version" ]
+if [ -n "$found_version" ]
 then
 
   # MySQL 8.0 in Ubuntu has a bug in packaging and the file is name wrongly
@@ -111,7 +133,7 @@ then
   fi
 
   if dpkg --compare-versions "$found_version" '>>' "$max_upgradeable_version" \
-  && dpkg --compare-versions "$found_version" '<<' "10.0"
+    && dpkg --compare-versions "$found_version" '<<' "10.0"
   then
     downgrade_detected=true
   fi
@@ -119,7 +141,9 @@ then
 fi
 
 # If there is no debian-*.flag, and no version was detected, but a file that
-# indicated MySQL 8.0 is found, assume so and trigger data directory moval.
+# indicated MySQL 8.0 is found (undo_001 is created by default in MySQL 8.0+
+# installs), then that file is enough of additional indication to trigger the
+# move of the data directory.
 if [ -z "$found_version" ] &&
    [ -z "$(find $mysql_datadir/debian-*.flag 2> /dev/null)" ] &&
    [ -f "$mysql_datadir/undo_001" ]
@@ -131,7 +155,7 @@ fi
 
 # Don't abort dpkg if downgrade is detected (as was done previously).
 # Instead simply move the old datadir and create a new for this_version.
-if [ ! -z "$downgrade_detected" ]
+if [ -n "$downgrade_detected" ]
 then
   db_input critical "mariadb-server/old_data_directory_saved" || true
   db_go
@@ -152,13 +176,14 @@ stop_server
 # If we use NIS then errors should be tolerated. It's up to the
 # user to ensure that the mysql user is correctly setup.
 # Beware that there are two ypwhich one of them needs the 2>/dev/null!
-if test -n "$(which ypwhich 2>/dev/null)"  &&  ypwhich >/dev/null 2>&1; then
+if test -n "$(command -v ypwhich 2>/dev/null)"  &&  ypwhich > /dev/null 2>&1
+then
   set +e
 fi
 
 #
 # Now we have to ensure the following state:
-# /etc/passwd: mysql:x:100:101:MySQL Server:/nonexistent:/bin/false
+# /etc/passwd: mysql:x:100:101:MariaDB Server:/nonexistent:/bin/false
 # /etc/group:  mysql:x:101:
 #
 # Sadly there could any state be present on the system so we have to
@@ -167,23 +192,25 @@ fi
 #
 
 # creating mysql group if he isn't already there
-if ! getent group mysql >/dev/null; then
- 	# Adding system group: mysql.
-	addgroup --system mysql >/dev/null
+if ! getent group mysql >/dev/null
+then
+  # Adding system group: mysql.
+  addgroup --system mysql >/dev/null
 fi
 
 # creating mysql user if he isn't already there
-if ! getent passwd mysql >/dev/null; then
-	# Adding system user: mysql.
-	adduser \
-	  --system \
-          --disabled-login \
-	  --ingroup mysql \
-	  --no-create-home \
-	  --home /nonexistent \
-	  --gecos "MySQL Server" \
-	  --shell /bin/false \
-	  mysql  >/dev/null 2>&1
+if ! getent passwd mysql >/dev/null
+then
+  # Adding system user: mysql.
+  adduser \
+    --system \
+    --disabled-login \
+    --ingroup mysql \
+    --no-create-home \
+    --home /nonexistent \
+    --gecos "MariaDB Server" \
+    --shell /bin/false \
+    mysql >/dev/null 2>&1
 fi
 
 # end of NIS tolerance zone
@@ -191,9 +218,11 @@ set -e
 
 # if there's a symlink, let's store where it's pointing, because otherwise
 # it's going to be lost in some situations
-for dir in DATADIR LOGDIR; do
+for dir in DATADIR LOGDIR
+do
   checkdir=$(eval echo "$"$dir)
-  if [ -L "$checkdir" ]; then
+  if [ -L "$checkdir" ]
+  then
     # Use mkdir option 'Z' to create with correct SELinux context.
     mkdir -pZ "$mysql_upgradedir"
     cp -dT "$checkdir" "$mysql_upgradedir/$dir.link"
@@ -201,13 +230,17 @@ for dir in DATADIR LOGDIR; do
 done
 
 # creating mysql home directory
-if [ ! -d $mysql_datadir ] && [ ! -L $mysql_datadir ]; then
-	# Use mkdir option 'Z' to create with correct SELinux context.
+if [ ! -d $mysql_datadir ] && [ ! -L $mysql_datadir ]
+then
+  # Use mkdir option 'Z' to create with correct SELinux context.
   mkdir -Z $mysql_datadir
 fi
 
-# checking disc space
-if LC_ALL=C BLOCKSIZE= df --portability $mysql_datadir/. | tail -n 1 | awk '{ exit ($4>1000) }'; then
+# As preset blocksize of GNU df is 1024 then available bytes is $df_available_blocks * 1024
+# 4096 blocks is then lower than 4 MB
+df_available_blocks="$(LC_ALL=C BLOCKSIZE='' df --output=avail "$mysql_datadir" | tail -n 1)"
+if [ "$df_available_blocks" -lt "4096" ]
+then
   echo "ERROR: There's not enough space in $mysql_datadir/" 1>&2
   db_stop
   exit 1
@@ -237,8 +270,9 @@ db_stop
 # disabled due to the mariadb-server-x.y.postrm being triggered.
 #   $1 = upgrade
 #   $2 = 1:10.6.11-2
-if [ "$1" = "upgrade" ] && [ -n "$2" ] && [ -e "/etc/init.d/mariadb" ] ; then
-	chmod +x "/etc/init.d/mariadb" >/dev/null || true
+if [ "$1" = "upgrade" ] && [ -n "$2" ] && [ -e "/etc/init.d/mariadb" ]
+then
+  chmod +x "/etc/init.d/mariadb" >/dev/null || true
 fi
 
 # dh_installinit/13.11.3 adds this check but with extra condition that there
@@ -248,6 +282,7 @@ fi
 # here without any expectation for '$2'. This ensures that upgrades from
 # mariadb-server-x.y to mariadb-server (without version suffix) ends up with the
 # executable bit set on /etc/init.d/mariadb.
-if [ "$1" = "install" ] && [ -e "/etc/init.d/mariadb" ] ; then
-	chmod +x "/etc/init.d/mariadb" >/dev/null || true
+if [ "$1" = "install" ] && [ -e "/etc/init.d/mariadb" ]
+then
+  chmod +x "/etc/init.d/mariadb" >/dev/null || true
 fi
diff --git a/debian/tests/smoke b/debian/tests/smoke
--- a/debian/tests/smoke
+++ b/debian/tests/smoke
@@ -27,7 +27,7 @@ set -ex
 # Start the daemon if it was not running. For example in Docker testing
 # environments there might not be any systemd et al and the service needs to
 # be started manually.
-if ! which systemctl
+if ! command -v systemctl
 then
   if ! /etc/init.d/mariadb status
   then
@@ -57,9 +57,10 @@ INSERT INTO foo (bar) VALUES (41);
 EOT
 
 result=$(echo 'SELECT bar+1 FROM foo;'|mysql --batch --skip-column-names --user=testuser --password=testpassword testdatabase)
-if [ "$result" != "42" ]; then
-       echo "Unexpected result" >&2
-       exit 1
+if [ "$result" != "42" ]
+then
+  echo "Unexpected result" >&2
+  exit 1
 fi
 
 mysql --user=testuser --password=testpassword testdatabase <<EOT
@@ -91,20 +92,21 @@ EOT
 plugin=mariadb-plugin-rocksdb
 if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
    [ "$(dpkg-architecture -qDEB_HOST_ARCH_ENDIAN)" = little ]
-  then
+then
   dpkg-query -W $plugin
 
   LOG=/var/lib/mysql/#rocksdb/LOG
   # XXX: The server may only be started during the install of
   #      mariadb-server, which happens before that of the plugin.
-  [ -e $LOG ] || mysql -e "INSTALL PLUGIN RocksDB SONAME 'ha_rocksdb';"
+  [ -e $LOG ] || mariadb -e "INSTALL PLUGIN RocksDB SONAME 'ha_rocksdb';"
   # XXX: rocksdb_supported_compression_types variable does not report ZSTD.
 
   # Print RocksDB supported items so test log is easier to debug
   grep -F " supported:" $LOG
 
   # Check that the expected compression methods are supported
-  for a in LZ4 Snappy Zlib ZSTD; do
+  for a in LZ4 Snappy Zlib ZSTD
+  do
     if ! grep -qE "k$a(Compression)? supported: 1" $LOG
     then
       # Fail with explicit error message
@@ -113,5 +115,9 @@ if [ "$(dpkg-architecture -qDEB_HOST_ARCH_BITS)" != 32 ] &&
     fi
   done
 else
-  ! dpkg-query -W $plugin
+  if dpkg-query -W $plugin
+  then
+    echo "Error: Plugin $plugin was found even though it should not exist on a 32-bit and little-endian system"
+    exit 1
+  fi
 fi
