chore: Update version to 1:11.5

diff --git a/debian/mariadb-server.preinst b/debian/mariadb-server.preinst
--- a/debian/mariadb-server.preinst
+++ b/debian/mariadb-server.preinst
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash
 #
 # summary of how this script can be called:
 #        * <new-preinst> install
@@ -6,6 +6,8 @@
 #        * <new-preinst> upgrade <old-version>
 #        * <old-preinst> abort-upgrade <new-version>
 #
+
+set -e
 
 # shellcheck source=/dev/null
 . /usr/share/debconf/confmodule
@@ -27,15 +29,6 @@ export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
 mysql_datadir=/var/lib/mysql
 mysql_upgradedir=/var/lib/mysql-upgrade
 
-MARIADBD_USERS="root"
-
-# Check if user 'mysql' exists before referring to it in pgrep
-# to avoid pgrep erroring on 'invalid user name'
-if id mysql >/dev/null 2>&1
-then
-  MARIADBD_USERS="$MARIADBD_USERS,mysql"
-fi
-
 # Try to stop the server in a sane way. If it does not success let the admin
 # do it himself. No database directories should be removed while the server
 # is running! Another mariadbd in e.g. a different chroot is fine for us.
@@ -43,7 +36,7 @@ stop_server() {
   # Return immediately if there are no mysqld processes running on a host
   # (leave containerized processes with the same name in other namespaces)
   # as there is no point in trying to shutdown in that case.
-  if ! pgrep -x -u "$MARIADBD_USERS" --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null
+  if ! pgrep -x --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null
   then
     return
   fi
@@ -86,9 +79,6 @@ do
     break
   fi
 
-  # The whole flag_version thing should be rewritten, so ignore minor Shellcheck
-  # nag for now
-  # shellcheck disable=SC2001
   flag_version=$(echo "$flag" | sed 's/.*debian-\([0-9\.]\+\).flag/\1/')
 
   # Initialize value if empty
@@ -176,14 +166,14 @@ stop_server
 # If we use NIS then errors should be tolerated. It's up to the
 # user to ensure that the mysql user is correctly setup.
 # Beware that there are two ypwhich one of them needs the 2>/dev/null!
-if test -n "$(command -v ypwhich 2>/dev/null)"  &&  ypwhich > /dev/null 2>&1
+if test -n "$(which ypwhich 2>/dev/null)"  &&  ypwhich >/dev/null 2>&1
 then
   set +e
 fi
 
 #
 # Now we have to ensure the following state:
-# /etc/passwd: mysql:x:100:101:MariaDB Server:/nonexistent:/bin/false
+# /etc/passwd: mysql:x:100:101:MySQL Server:/nonexistent:/bin/false
 # /etc/group:  mysql:x:101:
 #
 # Sadly there could any state be present on the system so we have to
@@ -208,9 +198,9 @@ then
     --ingroup mysql \
     --no-create-home \
     --home /nonexistent \
-    --gecos "MariaDB Server" \
+    --gecos "MySQL Server" \
     --shell /bin/false \
-    mysql >/dev/null 2>&1
+    mysql  >/dev/null
 fi
 
 # end of NIS tolerance zone
@@ -221,8 +211,7 @@ set -e
 for dir in DATADIR LOGDIR
 do
   checkdir=$(eval echo "$"$dir)
-  if [ -L "$checkdir" ]
-  then
+  if [ -L "$checkdir" ]; then
     # Use mkdir option 'Z' to create with correct SELinux context.
     mkdir -pZ "$mysql_upgradedir"
     cp -dT "$checkdir" "$mysql_upgradedir/$dir.link"
@@ -236,14 +225,23 @@ then
   mkdir -Z $mysql_datadir
 fi
 
-# As preset blocksize of GNU df is 1024 then available bytes is $df_available_blocks * 1024
-# 4096 blocks is then lower than 4 MB
-df_available_blocks="$(LC_ALL=C BLOCKSIZE='' df --output=avail "$mysql_datadir" | tail -n 1)"
-if [ "$df_available_blocks" -lt "4096" ]
+# Check if MariaDB datadir is available if not fails.
+# There should be symlink or directory available or something will fail.
+if [ -d "$mysql_datadir" ] || [ -L "$mysql_datadir" ]
 then
-  echo "ERROR: There's not enough space in $mysql_datadir/" 1>&2
-  db_stop
-  exit 1
+    # As preset blocksize of GNU df is 1024 then available bytes is $df_available_blocks * 1024
+    # 4096 blocks is then lower than 4 MB
+    df_available_blocks="$(LC_ALL=C BLOCKSIZE='' df --output=avail "$mysql_datadir" | tail -n 1)"
+    if [ "$df_available_blocks" -lt "4096" ]
+    then
+      echo "ERROR: There's not enough space in $mysql_datadir/" 1>&2
+      db_stop
+      exit 1
+    fi
+else
+    echo "ERROR: There's no directory or symlink available: $mysql_datadir/" 1>&2
+    db_stop
+    exit 1    
 fi
 
 # Since the home directory was created before putting the user into
@@ -262,27 +260,3 @@ set -e
 db_stop
 
 #DEBHELPER#
-
-# dh_installinit/13.11.3 adds this check but only with 'install', so we need to
-# have and extra one to check 'upgrade'. This ensures that upgrades from
-# mariadb-server-x.y to mariadb-server (without version suffix) ends up with
-# the executable bit set on /etc/init.d/mariadb, which otherwise would end up
-# disabled due to the mariadb-server-x.y.postrm being triggered.
-#   $1 = upgrade
-#   $2 = 1:10.6.11-2
-if [ "$1" = "upgrade" ] && [ -n "$2" ] && [ -e "/etc/init.d/mariadb" ]
-then
-  chmod +x "/etc/init.d/mariadb" >/dev/null || true
-fi
-
-# dh_installinit/13.11.3 adds this check but with extra condition that there
-# must be a version passed as '$2', but that will always be empty when install
-# runs after the unpack that is retriggered for package 'mariadb-server' when
-# the old 'mariadb-server-10.6' is purged, so we need to repeat the same check
-# here without any expectation for '$2'. This ensures that upgrades from
-# mariadb-server-x.y to mariadb-server (without version suffix) ends up with the
-# executable bit set on /etc/init.d/mariadb.
-if [ "$1" = "install" ] && [ -e "/etc/init.d/mariadb" ]
-then
-  chmod +x "/etc/init.d/mariadb" >/dev/null || true
-fi
